### ISSUE TITLE
Compass has changed how browser support is configured.

### ISSUE THREAD

**Issue by febstarer** [fladron/drupal7-base-files#2]
WARNING: Compass has changed how browser support is configured. 

The following configuration variables are no longer supported: $legacy-support-for-ie6, $legacy-support-for-ie7, $legacy-support-for-ie8.

Details: http://compass-style.org/help/documentation/tuning-vendor-prefixes/

**Comment by fladron** [comment]
Branch removed. The SASS version will be on fladron/d7basev2
